version: '3.9'
services:
  redis:
    image: redis:latest
    container_name: cache-server
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    env_file:
      - .env